[tool.poetry]
name = "WGM_api"
version = "0.1.18"
description = "A Python client library for managing WireGuard server users and sessions."
authors = ["Andrey Ivanov <andrey.ivanov.dev13@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.32.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[project.urls]
HomePage = "https://github.com/LostUnion/WGM"
