[build-system]
requires = ["poetry-core>=1.9.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "ddcDatabases"
version = "1.0.8"
description = "Custom Database Queries"
license = "MIT"
readme = "README.md"
authors = ["Daniel Costa <danieldcsta@gmail.com>"]
maintainers = ["Daniel Costa"]
repository = "https://github.com/ddc/ddcDatabases"
homepage = "https://github.com/ddc/ddcDatabases"
packages = [{include = "ddcDatabases"}]
package-mode = true
keywords = ["python3", "databases", "ddcDatabases"]
classifiers = [
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Development Status :: 5 - Production/Stable",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Environment :: Other Environment",
    "Intended Audience :: Developers",
    "Natural Language :: English",
]

[tool.poetry.group.test]
optional = true

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
pydantic-settings = ">=2.6.1"
SQLAlchemy = ">=2.0.36"
pyodbc = ">=5.2.0"
aioodbc = ">=0.5.0"
psycopg2 = "^2.9.10"
asyncpg = "^0.30.0"
pytest = "^8.3.3"

[tool.poetry.extras]
mssql = [ "pyodbc", "aioodbc" ]
pgsql = [ "psycopg2", "asyncpg" ]
all = [ "pyodbc", "aioodbc", "psycopg2", "asyncpg" ]

[tool.poetry.group.test.dependencies]
pytest = ">=8.3.3"
faker = ">=33.0.0"
coverage = ">=7.6.8"
