[project]
name = "nuclia-models"
version = "0.18.2"
description = ""
dependencies = [
    "pydantic[email]>=2.9.2",
]
requires-python = ">=3.9"
readme = "README.md"

[build-system]
requires = [
    "pdm-backend",
]
build-backend = "pdm.backend"

[tool.pdm]
distribution = true

[tool.pdm.dev-dependencies]
dev = [
    "ruff==0.6.9",
    "pytest>=8.3.3",
    "mypy>=1.13.0",
]

[tool.mypy]
strict = true

[tool.ruff]
target-version = "py39"
line-length = 110

[tool.ruff.lint]
select = [
    "E",
    "W",
    "C90",
    "F",
    "I",
    "C4",
    "B",
    "N",
    "UP",
    "YTT",
    "S",
    "BLE",
    "FBT",
    "COM",
    "T10",
    "EM",
    "EXE",
    "ISC",
    "ICN",
    "G",
    "INP",
    "PIE",
    "T20",
    "PYI",
    "PT",
    "Q",
    "RSE",
    "RET",
    "SLF",
    "SIM",
    "TID",
    "TCH",
    "INT",
    "PTH",
    "ERA",
    "PGH",
    "PL",
    "TRY",
    "RUF",
]
ignore = [
    "B008",
    "PT004",
    "PT007",
    "FBT003",
    "TRY301",
    "SIM105",
    "W191",
    "E111",
    "E114",
    "E117",
    "D206",
    "D300",
    "Q000",
    "Q001",
    "Q002",
    "Q003",
    "COM812",
    "COM819",
    "ISC001",
    "ISC002",
    "PGH004",
    "PT003",
    "B006",
    "BLE001",
    "TRY003",
    "TRY002",
    "EM102",
    "PTH",
    "ERA001",
    "S113",
    "PLR2004",
    "PLR0913",
    "PLR0915",
    "N818",
    "SIM117",
    "FBT001",
    "FBT002",
    "PLW0603",
    "E721",
    "E501",
    "PLR0912",
    "C901",
    "PGH003",
    "B904",
    "RUF012",
    "N805",
    "N802",
    "N803",
    "SLF001",
    "PYI036",
    "N801",
    "N816",
    "G004",
    "UP006",
    "UP035",
    "SIM401",
    "PT023",
    "F541",
    "PT022",
    "INP001",
    "RET505",
    "TCH002",
    "SIM115",
    "C408",
    "PT024",
    "C417",
    "S104",
    "UP026",
    "UP031",
    "TRY201",
    "TRY302",
    "B011",
    "PT015",
    "E722",
    "SIM300",
    "UP032",
    "SIM118",
    "PT001",
    "TRY300",
    "SIM102",
    "UP004",
    "EM101",
    "RUF010",
    "RSE102",
    "RUF100",
    "S324",
    "RUF013",
    "SIM108",
    "S101",
    "RET504",
    "RET506",
    "TCH003",
    "UP009",
    "S110",
    "RET503",
    "PLW2901",
    "TID252",
    "PLC0414",
    "S301",
    "F841",
    "T201",
    "UP007",
    "PLR1714",
    "B007",
    "SIM110",
    "W291",
    "SIM113",
    "RET502",
    "UP030",
    "RUF015",
    "SIM114",
    "PT018",
    "RUF005",
    "UP039",
    "C416",
    "S105",
    "PLR0911",
    "B009",
    "PT017",
    "TCH001",
    "C401",
    "UP015",
    "B023",
    "C403",
    "C419",
    "PLR0402",
    "RUF002",
    "N806",
    "PLR0402",
    "B026",
    "PLR1711",
    "SIM910",
    "F601",
]

[tool.ruff.lint.flake8-tidy-imports]
ban-relative-imports = "all"

[tool.ruff.lint.pyupgrade]
keep-runtime-typing = true
