[project]
name = "bytewax-lever"
version = "0.2.2"
description = "Lever connectors for Bytewax"
readme = "README.md"
authors = [
    { name = "James Ward", email = "james@notjam.es" }
]
license = { file = "LICENSE" }
keywords = [ "bytewax", "lever" ]
requires-python = ">=3.12"
dependencies = [
    "bytewax>=0.21.0",
    "requests>=2.32.3",
]

[project.urls]
Repository = "https://github.com/imnotjames/bytewax-lever.git"
Issues = "https://github.com/imnotjames/bytewax-lever/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest-mock>=3.14.0",
    "pytest>=8.3.3",
]
