[tool.poetry]
name = "docker_analyzer"
version = "0.1.0"
description = "A lightweight to tool to analyse and compare Docker images instantly, focusing on layer analysis"
authors = ["Gianfrancesco Angelini <gian.angelini@hotmail.com>"]
readme = "README.md"
packages = [
    { include = "docker_analyzer" },
]

[tool.poetry.dependencies]
python = ">=3.10,<3.14"

inquirerpy = "^0.3.4"
numpy = "^2.1.1"
docker = "^7.1.0"
pandas = "^2.2.2"
rich = "^13.8.1"
urwid = "^2.6.15"
keyboard = "^0.13.5"
textual = "^0.79.1"
flask = "^3.0.3"
beautifulsoup4 = "^4.12.3"
pyyaml = "^6.0.2"
toml = "^0.10.2"
anytree = "^2.12.1"

[tool.poetry.group.dev.dependencies]
black = "^24.8.0"
pre-commit = "^3.8.0"
jupyter = "^1.1.1"
pytest = "^8.3.3"
pyinstaller = "^6.10.0"
pydantic = "^2.9.2"
mypy = "^1.11.2"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
docker_analyzer = "docker_analyzer.cli.cli:cli"
