[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nanocontroller"
version = "1.0.2"
description = "NanoLeaf controller"
readme = {file = "README.md", content-type = "text/markdown"}
authors = [
    {name = "Jared Gantt", email = "jaredgantt@gmail.com"}
]
requires-python = ">=3.6"
keywords = ["nanoleaf"]
license = {text = "MIT"}
urls = {Homepage = "https://github.com/JJGantt/nano_control"}

dependencies = [
    "openmeteo_requests==1.3.0",
    "numpy==2.1.3",
    "openmeteo_sdk==1.18.0",
    "pandas==2.2.3",
    "python-dotenv==1.0.1",
    "httpx==0.27.2",
    "requests==2.32.3",
    "retry-requests==2.0.0",
    "requests-cache==1.2.1"
]

