[project]
name = "fryhcs"
version = "0.2.42"
keywords = [
    "fryhcs",
    "fry",
    "django",
    "flask",
]
authors = [{name="Zenk Ju", email="juzejian@gmail.com"},]
description = "A python library to generate HTML, Javascript and CSS, based on fry file"
license = "MIT"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "parsimonious",
    "flask",
    "coloraide",
]

[project.urls]
Homepage = "https://github.com/frybox/fryhcs"
"Bug Tracker" = "https://github.com/frybox/fryhcs/issues"
Source = "https://github.com/frybox/fryhcs"

[project.scripts]
fry = "fryhcs.cmdline:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

