[tool.poetry]
name = "dumbo-utils"
version = "0.3.6"
description = "Different utilities to be reused in other projects"
authors = ["Mario Alviano <mario.alviano@gmail.com>"]
readme = "README.md"
packages = [{include = "dumbo_utils"}]

[tool.poetry.dependencies]
python = "^3.11"
rich = "^13.7.1"
typer = "^0.12.3"
typeguard = "^4.2.1"
valid8 = "^5.1.2"
distlib = "^0.3.8"
dataclass-type-validator = "^0.1.2"

[tool.poetry.group.dev.dependencies]
coverage = "^7.5.1"
pytest = "^8.2.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
