name: All tests on Kafka MQ
on:
  pull_request:
    branches: [ "dev", "main" ]
    types: [opened, synchronize, reopened]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40
    if: "!contains(github.event.head_commit.message, 'CI Bot')"

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"

      - name: Install package and dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[all]
          python -m pip install .[ml_dev]

      - name: Run docker compose
        run: docker compose -f deployment/compose-kafka.yml up -d

      - name: Wait for one minute
        run: sleep 60

      - name: Check liveness
        run: |
          export MQ_TYPE=kafka
          export MQ_PORT=9092
          python -c 'from flowcept.configs import MQ_TYPE, MQ_PORT; print(f"MQ_TYPE={MQ_TYPE}"); print(f"MQ_PORT={MQ_PORT}")'
          python -c 'from flowcept import Flowcept; assert Flowcept.services_alive()'

      - name: Run tests with kafka
        run: |
          export MQ_TYPE=kafka
          export MQ_PORT=9092
          pytest --ignore=tests/decorator_tests/ml_tests/llm_tests

      - name: Test notebooks
        run: pytest --ignore=notebooks/zambeze.ipynb --nbmake "notebooks/" --nbmake-timeout=600 --ignore=notebooks/dask_from_CLI.ipynb

#      - name: Test notebooks
#        run: |
#          pip install -e .[all] # Installing stuff again may not be needed
#          export MQ_TYPE=kafka
#          export MQ_PORT=9092
#          python -c 'from flowcept.configs import MQ_TYPE, MQ_PORT; print(f"MQ_TYPE={MQ_TYPE}"); print(f"MQ_PORT={MQ_PORT}")'
#          python -c 'from flowcept import Flowcept; assert Flowcept.services_alive()'
#          pytest --ignore=notebooks/zambeze.ipynb --nbmake "notebooks/" --nbmake-timeout=600 --ignore=notebooks/dask_from_CLI.ipynb
