[project]
name = "golem-cert-companion"
version = "0.2.3"
description = "Certificate companion for Golem"
authors = [{name = "Phillip", email = "phillip@golem.network"}]
dependencies = [
    "colorama>=0.4.4",
    "python-dateutil>=2.8.2", 
    "requests>=2.28.0",
    "pathlib>=1.0.1"
]
requires-python = ">=3.8"

[project.urls]
Homepage = "https://github.com/golemfactory/golem-cert-companion"

[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project.scripts]
golem-cert-companion = "golem_cert_companion.certificate_manager:main"
gcert = "golem_cert_companion.certificate_manager:main"