[tool.poetry]
name = "botrun-flow-lang"
version = "4.11.271"
description = "A flow language for botrun"
authors = ["sebastian-hsu <sebastian.hsu@gmail.com>"]
readme = "README.md"
packages = [
    { include = "botrun_flow_lang" },
]

[tool.poetry.dependencies]
python = "^3.11"
fastapi = "^0.115.5"
uvicorn = "^0.25.0"
pydantic-settings = "^2.5.2"
google-auth = "^2.35.0"
google-cloud-storage = "^2.18.2"
google-cloud-firestore = "^2.19.0"
aiohttp = "^3.10.8"
pytz = "^2024.2"
pyyaml = "^6.0.2"
deepdiff = "^8.0.1"
litellm = "^1.48.8"
vertexai = "^1.71.1"
google-cloud-discoveryengine = "^0.13.3"
langchain-core = "^0.3.15"
langchain = "^0.3.7"
langgraph = "^0.2.45"

[tool.poetry.dev-dependencies]
build = "^1.2.2.post1"
twine = "^5.1.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
